import { test, expect } from '@playwright/test'
import JSZip from 'jszip'
import { readFile } from 'node:fs/promises'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  // Refuse to run mutating preview tests against a configured cloud workspace.
  await expect(page.locator('.preview-badge')).toHaveCount(1)
})

test('article renders real code, table, image, TOC and persisted collapse', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/notes/java-getting-started')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('JavaSE - Java入门')
  await expect(page.locator('.line-numbers span')).toHaveCount(9)
  await expect(page.locator('.hljs-keyword').first()).toBeVisible()
  await expect(page.locator('.prose-content table tr')).toHaveCount(4)
  await expect(page.locator('.prose-content ol li')).toHaveCount(3)
  await expect(page.locator('.prose-content a[href="https://dev.java/learn/"]')).toBeVisible()
  await expect(page.locator('.toc nav a')).toHaveCount(4)
  const image = page.locator('.article-image img')
  await image.scrollIntoViewIfNeeded()
  await expect.poll(() => image.evaluate((element: HTMLImageElement) => element.naturalWidth)).toBe(1200)
  await page.evaluate(() => scrollTo(0, 0))
  await page.screenshot({ path: '.local/article-desktop.png', fullPage: true })
  await page.getByRole('button', { name: '隐藏教程' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await expect.poll(() => page.locator('.tutorial-body').evaluate(element => element.getBoundingClientRect().height)).toBe(0)
  await expect(page.locator('.toc')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('button', { name: '显示教程' })).toBeVisible()
  await page.locator('.article-pagination a').last().click()
  await expect(page.getByRole('button', { name: '显示教程' })).toBeVisible()
  await page.getByRole('button', { name: '显示教程' }).click()
  await expect(page.getByRole('button', { name: '隐藏教程' })).toBeVisible()
  expect(errors).toEqual([])
})

test('home filters categories and searches title and body', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.note-row')).toHaveCount(5)
  await page.screenshot({ path: '.local/home-desktop.png', fullPage: true })
  await page.getByRole('tab', { name: '数据库', exact: true }).click()
  await expect(page.locator('.note-row')).toHaveCount(1)
  await page.getByRole('searchbox').fill('字节码')
  await page.getByRole('button', { name: '开始搜索' }).click()
  await expect(page.locator('.note-row')).toHaveCount(1)
  await expect(page.locator('.note-row')).toContainText('Java入门')
  await page.getByRole('searchbox').fill('不存在的关键词XYZ')
  await page.getByRole('button', { name: '开始搜索' }).click()
  await expect(page.getByRole('heading', { name: '没有找到笔记' })).toBeVisible()
})

test('mobile drawer, narrow layout and collapse work', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/notes/java-getting-started')
  await expect(page.getByRole('button', { name: '打开导航' })).toBeVisible()
  await page.getByRole('button', { name: '打开导航' }).click()
  await expect(page.locator('.sidebar')).toHaveClass(/is-open/)
  await page.getByRole('link', { name: '查询与筛选', exact: true }).click()
  await expect(page.locator('.sidebar')).not.toHaveClass(/is-open/)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('SQL - 查询与筛选')
  await page.goto('/notes/java-getting-started')
  await page.screenshot({ path: '.local/article-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: '隐藏教程' }).click()
  await expect.poll(() => page.locator('.tutorial-body').evaluate(element => element.getBoundingClientRect().height)).toBe(0)
  await page.setViewportSize({ width: 320, height: 740 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  const title = await page.getByRole('heading', { level: 1 }).boundingBox()
  const toggle = await page.getByRole('button', { name: '显示教程' }).boundingBox()
  expect(title!.x + title!.width).toBeLessThanOrEqual(toggle!.x)
})

test('Tiptap edits autosave and survive reload; publishing is functional', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/admin')
  await page.getByRole('button', { name: '新建笔记' }).click()
  const title = page.getByRole('textbox', { name: '文章标题' })
  await title.fill('自动保存验证笔记')
  await page.getByRole('button', { name: '生成', exact: true }).click()
  await page.locator('.tiptap').fill('编辑器里的测试正文')
  await expect(page.locator('.save-state')).toHaveText('已保存', { timeout: 15000 })
  await page.reload()
  await expect(title).toHaveValue('自动保存验证笔记')
  await expect(page.locator('.tiptap')).toContainText('编辑器里的测试正文')
  await page.getByRole('checkbox', { name: '发布文章' }).check()
  await expect(page.locator('.save-state')).toHaveText('已保存', { timeout: 15000 })
  await page.screenshot({ path: '.local/editor-desktop.png', fullPage: true })
  await page.goto('/notes/' + encodeURIComponent('自动保存验证笔记'))
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('自动保存验证笔记')
  await expect(page.locator('.prose-content')).toContainText('编辑器里的测试正文')
  expect(errors).toEqual([])
})

test('zip backup contains five markdown notes, original data and real image', async ({ page }) => {
  await page.goto('/admin')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出备份' }).click()
  const download = await downloadPromise
  const path = await download.path()
  expect(path).toBeTruthy()
  const zip = await JSZip.loadAsync(await readFile(path!))
  const markdown = Object.keys(zip.files).filter(file => file.endsWith('.md'))
  expect(markdown).toHaveLength(5)
  const java = await zip.file(markdown.find(file => file.includes('java-getting-started'))!)!.async('string')
  expect(java).toContain('```java')
  expect(java).toContain('public class HelloNote')
  expect(java).toContain('../assets/image-1.png')
  expect(java).toContain('|')
  const source = JSON.parse(await zip.file('notebook.json')!.async('string'))
  expect(source.notes).toHaveLength(5)
  const image = await zip.file('assets/image-1.png')!.async('uint8array')
  expect(image.byteLength).toBeGreaterThan(1000)
  await download.saveAs('.local/verified-backup.zip')
})

test('category CRUD and occupied category guard', async ({ page }) => {
  await page.goto('/admin/categories')
  await page.getByLabel('分类名称').fill('网络基础')
  await page.getByLabel('Slug', { exact: true }).fill('network')
  await page.getByRole('button', { name: '添加分类' }).click()
  await expect(page.locator('.management-summary').filter({ hasText: '网络基础' })).toBeVisible()
  await page.getByRole('button', { name: '编辑分类 网络基础', exact: true }).click()
  await page.getByLabel('分类名称').fill('计算机网络')
  await page.getByRole('button', { name: '保存分类' }).click()
  await expect(page.locator('.management-summary').filter({ hasText: '计算机网络' })).toBeVisible()
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除分类 JAVA', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('请先移动或删除')
  await page.getByRole('button', { name: '删除分类 计算机网络', exact: true }).click()
  await expect(page.locator('.management-summary').filter({ hasText: '计算机网络' })).toHaveCount(0)
})

test('editor code language, table tools, image sizing and attachments are real', async ({ page }) => {
  await page.goto('/admin/notes/20000000-0000-4000-8000-000000000001')
  await page.locator('.tiptap pre').click()
  await expect(page.getByLabel('代码语言')).toHaveValue('java')
  await page.getByLabel('代码语言').selectOption('cpp')
  await expect(page.locator('.tiptap pre code')).toHaveClass(/language-cpp/)
  await page.getByLabel('代码语言').selectOption('java')
  await page.locator('.tiptap td').first().click()
  await page.getByRole('button', { name: '在下方添加行', exact: true }).click()
  await expect(page.locator('.tiptap tr')).toHaveCount(5)
  const png = (await readFile('public/images/java-workflow.png')).toString('base64')
  await page.locator('.tiptap > p').last().click()
  await page.evaluate(base64 => {
    const bytes = Uint8Array.from(atob(base64), char => char.charCodeAt(0))
    const transfer = new DataTransfer()
    transfer.items.add(new File([bytes], 'pasted-diagram.png', { type: 'image/png' }))
    document.querySelector('.tiptap')!.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }))
  }, png)
  const pastedImage = page.locator('.tiptap img[src^="data:image/png"]')
  await expect(pastedImage).toHaveCount(1)
  await pastedImage.click()
  await expect(page.getByLabel('图片宽度')).toBeVisible()
  await page.getByLabel('图片宽度').fill('55')
  await expect(pastedImage).toHaveAttribute('width', '55%')
  const chooserPromise = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: '添加附件', exact: true }).click()
  const chooser = await chooserPromise
  await chooser.setFiles({ name: 'reference.txt', mimeType: 'text/plain', buffer: Buffer.from('attachment verification') })
  await expect(page.locator('.attachment-node')).toContainText('reference.txt')
  await expect(page.locator('.save-state')).toHaveText('已保存', { timeout: 15000 })
  await page.evaluate(() => scrollTo(0, 0))
  await page.screenshot({ path: '.local/editor-rich-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '.local/editor-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.reload()
  await expect(pastedImage).toHaveCount(1)
  await expect(pastedImage).toHaveAttribute('width', '55%')
  await expect(page.locator('.attachment-node')).toContainText('reference.txt')
  await expect(page.locator('.tiptap tr')).toHaveCount(5)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出当前笔记' }).click()
  const download = await downloadPromise
  const zip = await JSZip.loadAsync(await readFile((await download.path())!))
  const attachmentName = Object.keys(zip.files).find(name => name.startsWith('attachments/') && name.endsWith('reference.txt'))
  expect(attachmentName).toBeTruthy()
  expect(await zip.file(attachmentName!)!.async('string')).toBe('attachment verification')
  const markdownName = Object.keys(zip.files).find(name => name.endsWith('.md'))!
  expect(await zip.file(markdownName)!.async('string')).toContain('../attachments/')
  await page.goto('/notes/java-getting-started')
  await expect(page.locator('.image-preview-trigger').filter({ has: page.locator('img[alt="pasted-diagram.png"]') })).toHaveAttribute('style', 'width: 55%;')
  await expect(page.locator('.article-attachment')).toContainText('reference.txt')
})

test('invalid slug does not claim saved and current draft can still be exported', async ({ page }) => {
  await page.goto('/admin/notes/20000000-0000-4000-8000-000000000001')
  await page.getByRole('textbox', { name: '文章 slug' }).fill('invalid/slug')
  await page.getByRole('button', { name: '立即保存' }).click()
  await expect(page.locator('.save-state')).toHaveText('未保存')
  await expect(page.getByRole('alert')).toContainText('slug')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出当前笔记' }).click()
  const file = await downloadPromise
  const zip = await JSZip.loadAsync(await readFile((await file.path())!))
  const data = JSON.parse(await zip.file('notebook.json')!.async('string'))
  expect(data.notes[0].slug).toBe('invalid/slug')
  await page.getByRole('textbox', { name: '文章 slug' }).fill('java-common-errors')
  await page.getByRole('button', { name: '立即保存' }).click()
  await expect(page.getByRole('alert')).toContainText('已被其他笔记使用')
  await page.getByRole('textbox', { name: '文章 slug' }).fill('java-getting-started')
  await page.getByRole('link', { name: '笔记管理', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('笔记管理')
})

test('draft visibility, unpublish, delete and draft backup', async ({ page }) => {
  await page.goto('/admin')
  await page.getByRole('button', { name: '新建笔记' }).click()
  await page.getByRole('textbox', { name: '文章标题' }).fill('只存在于草稿中的标题')
  await page.getByRole('button', { name: '立即保存' }).click()
  await expect(page.locator('.save-state')).toHaveText('已保存')
  await page.getByRole('link', { name: '笔记管理', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出备份' }).click()
  const download = await downloadPromise
  const zip = await JSZip.loadAsync(await readFile((await download.path())!))
  expect(Object.keys(zip.files).filter(file => file.endsWith('.md'))).toHaveLength(6)
  await page.goto('/?q=' + encodeURIComponent('只存在于草稿中的标题'))
  await expect(page.locator('.note-row')).toHaveCount(0)
  await page.goto('/admin')
  await page.getByRole('button', { name: '下架 JavaSE - Java入门', exact: true }).click()
  await expect(page.getByRole('button', { name: '发布 JavaSE - Java入门', exact: true })).toBeVisible()
  await page.goto('/notes/java-getting-started')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('尚未发布')
  await page.goto('/admin')
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '删除 只存在于草稿中的标题', exact: true }).click()
  await expect(page.locator('.management-summary').filter({ hasText: '只存在于草稿中的标题' })).toHaveCount(0)
})

test('font color survives autosave, public rendering and export, and can be reset', async ({ page }) => {
  await page.goto('/admin')
  await page.getByRole('button', { name: '新建笔记' }).click()
  const editUrl = page.url()
  await page.getByRole('textbox', { name: '文章标题' }).fill('字体颜色验证')
  await page.getByRole('button', { name: '生成', exact: true }).click()
  const body = page.locator('.tiptap')
  await body.fill('需要强调的一段文字')
  await body.press('ControlOrMeta+a')
  await page.getByRole('button', { name: '加粗', exact: true }).click()
  await page.getByRole('button', { name: '字体颜色', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '选择字体颜色' })).toBeVisible()
  await page.screenshot({ path: '.local/text-color-desktop.png' })
  await page.getByRole('button', { name: '红色', exact: true }).click()
  await expect(body.locator('span[style]').first()).toHaveCSS('color', 'rgb(199, 57, 57)')
  await expect(body.locator('strong')).toHaveCSS('color', 'rgb(199, 57, 57)')
  await page.getByRole('checkbox', { name: '发布文章' }).check()
  await expect(page.locator('.save-state')).toHaveText('已保存')
  await page.reload()
  await expect(body.locator('span[style]').first()).toHaveCSS('color', 'rgb(199, 57, 57)')
  await page.goto('/notes/' + encodeURIComponent('字体颜色验证'))
  await expect(page.locator('.prose-content span[style]').first()).toHaveCSS('color', 'rgb(199, 57, 57)')
  const downloadPromise = page.waitForEvent('download')
  await page.goto(editUrl)
  await page.getByRole('button', { name: '导出当前笔记' }).click()
  const file = await downloadPromise
  const zip = await JSZip.loadAsync(await readFile((await file.path())!))
  const markdownFile = Object.keys(zip.files).find(name => name.endsWith('.md'))!
  expect(await zip.file(markdownFile)!.async('string')).toContain('style="color: #c73939"')
  const source = JSON.parse(await zip.file('notebook.json')!.async('string'))
  expect(JSON.stringify(source.notes[0].content)).toContain('#c73939')
  await body.click()
  await body.press('ControlOrMeta+a')
  await page.getByRole('button', { name: '字体颜色', exact: true }).click()
  await page.getByRole('button', { name: '恢复默认颜色', exact: true }).click()
  await expect(body.locator('span[style*="color"]')).toHaveCount(0)
  await expect(body.locator('strong')).toHaveCount(1)
  await expect(page.locator('.save-state')).toHaveText('已保存')
  await page.reload()
  await expect(body.locator('span[style*="color"]')).toHaveCount(0)
})

test('custom font colors work on mobile without overflowing or losing selection', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/admin/notes/20000000-0000-4000-8000-000000000001')
  const body = page.locator('.tiptap')
  await body.fill('手机颜色测试')
  await body.press('ControlOrMeta+a')
  await page.getByRole('button', { name: '字体颜色', exact: true }).click()
  const panel = page.getByRole('dialog', { name: '选择字体颜色' })
  await expect(panel).toBeVisible()
  await page.screenshot({ path: '.local/text-color-mobile.png' })
  let bounds = await panel.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
  await page.getByRole('textbox', { name: '颜色值', exact: true }).fill('invalid')
  await expect(page.getByRole('button', { name: '应用', exact: true })).toBeDisabled()
  await page.getByRole('textbox', { name: '颜色值', exact: true }).fill('#157a63')
  await page.getByRole('button', { name: '应用', exact: true }).click()
  await expect(body.locator('span[style]').first()).toHaveCSS('color', 'rgb(21, 122, 99)')
  await page.getByRole('button', { name: '字体颜色', exact: true }).click()
  await page.setViewportSize({ width: 320, height: 740 })
  await expect.poll(async () => {
    bounds = await panel.boundingBox()
    return bounds!.x + bounds!.width
  }).toBeLessThanOrEqual(320)
  await page.keyboard.press('Escape')
  await expect(panel).toHaveCount(0)
  await expect(page.locator('.save-state')).toHaveText('已保存')
  await page.reload()
  await expect(body.locator('span[style]').first()).toHaveCSS('color', 'rgb(21, 122, 99)')
})
